# Data Cleaning and Preprocessing

Data cleaning is an important step in data analysis and machine learning. Raw datasets often contain missing values, duplicate records, inconsistent formats, or categorical variables that cannot be directly used in machine learning models.

In this section, we will clean the dataset and prepare it for modeling by:

- Handling missing values
- Removing duplicate records
- Fixing inconsistent values
- Converting data types
- Encoding categorical variables

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("day1_ml_output.csv")

In [4]:
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [5]:
df.isnull().sum()

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['Education_Level'].unique()

<ArrowStringArray>
[  'High School',      'Graduate',    'Uneducated',       'Unknown',
       'College', 'Post-Graduate',     'Doctorate']
Length: 7, dtype: str

In [8]:
df['Education_Level'] = df['Education_Level'].replace('Unknown','Other')

## Fixing Inconsistent Values

Some categorical variables contained inconsistent values such as `"Unknown"`. These values were replaced with a more general category to maintain consistency.

In [9]:
df.dtypes

CLIENTNUM                     int64
Attrition_Flag                  str
Customer_Age                  int64
Gender                          str
Dependent_count               int64
Education_Level                 str
Marital_Status                  str
Income_Category                 str
Card_Category                   str
Months_on_book                int64
Total_Relationship_Count      int64
Months_Inactive_12_mon        int64
Contacts_Count_12_mon         int64
Credit_Limit                float64
Total_Revolving_Bal           int64
Avg_Open_To_Buy             float64
Total_Amt_Chng_Q4_Q1        float64
Total_Trans_Amt               int64
Total_Trans_Ct                int64
Total_Ct_Chng_Q4_Q1         float64
Avg_Utilization_Ratio       float64
dtype: object

## Label Encoding (Binary Categories)

Binary categorical variables such as `Gender` and `Attrition_Flag` were converted into numerical values using Label Encoding. This allows machine learning algorithms to process the data.

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['Attrition_Flag'] = le.fit_transform(df['Attrition_Flag'])

## One-Hot Encoding (Multiple Categories)

Categorical variables with multiple categories were transformed using One-Hot Encoding. This method creates separate binary columns for each category and prevents models from interpreting categorical values as ordinal relationships.

In [11]:
df = pd.get_dummies(df, columns=[
    'Education_Level',
    'Marital_Status',
    'Income_Category',
    'Card_Category'
])

In [12]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [13]:
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,...,Income_Category_$120K +,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Income_Category_Less than $40K,Income_Category_Unknown,Card_Category_Blue,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
0,768805383,1,45,1,3,39,5,1,3,12691.0,...,0,0,1,0,0,0,1,0,0,0
1,818770008,1,49,0,5,44,6,1,2,8256.0,...,0,0,0,0,1,0,1,0,0,0
2,713982108,1,51,1,3,36,4,1,0,3418.0,...,0,0,0,1,0,0,1,0,0,0
3,769911858,1,40,0,4,34,3,4,1,3313.0,...,0,0,0,0,1,0,1,0,0,0
4,709106358,1,40,1,3,21,5,1,0,4716.0,...,0,0,1,0,0,0,1,0,0,0

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CLIENTNUM                       10127 non-null  int64
 1   Attrition_Flag                  10127 non-null  int64
 2   Customer_Age                    10127 non-null  int64
 3   Gender                          10127 non-null  int64
 4   Dependent_count                 10127 non-null  int64
 5   Months_on_book                  10127 non-null  int64
 6   Total_Relationship_Count        10127 non-null  int64
 7   Months_Inactive_12_mon          10127 non-null  int64
 8   Contacts_Count_12_mon           10127 non-null  int64
 9   Credit_Limit                    10127 non-null  float64
 10  Total_Revolving_Bal             10127 non-null  int64
 11  Avg_Open_To_Buy                 10127 non-null  float64
 12  Total_Amt_Chng_Q4_Q1            10127 non-null  float64
 13  Total_Trans_Amt                 10127 non-null  int64
 14  Total_Trans_Ct                  10127 non-null  int64
 15  Total_Ct_Chng_Q4_Q1             10127 non-null  float64
 16  Avg_Utilization_Ratio           10127 non-null  float64
 17  Education_Level_College         10127 non-null  int64
 18  Education_Level_Doctorate       10127 non-null  int64
 19  Education_Level_Graduate        10127 non-null  int64
 20  Education_Level_High School     10127 non-null  int64
 21  Education_Level_Other           10127 non-null  int64
 22  Education_Level_Post-Graduate   10127 non-null  int64
 23  Education_Level_Uneducated      10127 non-null  int64
 24  Marital_Status_Divorced         10127 non-null  int64
 25  Marital_Status_Married          10127 non-null  int64
 26  Marital_Status_Single           10127 non-null  int64
 27  Marital_Status_Unknown          10127 non-null  int64
 28  Income_Category_$120K +         10127 non-null  int64
 29  Income_Category_$40K - $60K     10127 non-null  int64
 30  Income_Category_$60K - $80K     10127 non-null  int64
 31  Income_Category_$80K - $120K    10127 non-null  int64
 32  Income_Category_Less than $40K  10127 non-null  int64
 33  Income_Category_Unknown         10127 non-null  int64
 34  Card_Category_Blue              10127 non-null  int64
 35  Card_Category_Gold              10127 non-null  int64
 36  Card_Category_Platinum          10127 non-null  int64
 37  Card_Category_Silver            10127 non-null  int64
dtypes: float64(5), int64(33)
memory usage: 2.9 MB

## Conclusion

After preprocessing, the dataset is now clean and ready for feature engineering and modeling.

In [15]:
df.to_csv("day2_ml_output.csv", index=False)